// Generated by CoffeeScript 1.3.3
(function() {
  var file, nodestatic;

  nodestatic = require("node-static");

  file = new nodestatic.Server(".", {
    cache: 7200
  });

  require("http").createServer(function(request, response) {
    return request.addListener("end", function() {
      response.setHeader("Access-Control-Allow-Origin", "*");
      return file.serve(request, response, function(err, res) {
        if (err) {
          console.error("> Error serving " + request.url + " - " + err.message);
          response.writeHead(err.status, err.headers);
          return response.end();
        } else {
          return console.log("> " + request.url + " - " + res.message);
        }
      });
    });
  }).listen(8080);

  console.log("> node-static is listening on http://127.0.0.1:8080");

}).call(this);
