// Generated by CoffeeScript 1.3.3
(function() {

  (function() {
    var config1, config2, htmlReporter, intrvl, jasmineEnv, l1, l2;
    jasmineEnv = jasmine.getEnv();
    jasmineEnv.updateInterval = 1000;
    htmlReporter = new jasmine.HtmlReporter();
    jasmineEnv.addReporter(htmlReporter);
    jasmineEnv.specFilter = function(spec) {
      return htmlReporter.specFilter(spec);
    };
    l1 = l2 = false;
    config1 = {
      baseUrl: "scripts",
      paths: {
        "jquery-1.7.1": "lib/jquery-1.7.1",
        "jquery-1.8.2": "lib/jquery-1.8.2"
      },
      context: "context1"
    };
    config2 = {
      context: "context2",
      paths: {
        "jquery-1.7.1": "http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min",
        "jquery-1.8.2": "http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min"
      }
    };
    config2.baseUrl = config1.baseUrl;
    require(config1, ["specs/tests"], function(tests) {
      tests.init(config1.context);
      return l1 = true;
    });
    require(config2, ["specs/tests"], function(tests) {
      tests.init(config2.context);
      return l2 = true;
    });
    return intrvl = setInterval(function() {
      if (l1 && l2) {
        clearInterval(intrvl);
        return jasmineEnv.execute();
      }
    }, 10);
  })();

}).call(this);
