// Generated by CoffeeScript 1.3.3
(function() {

  define(["getJQuery!1.7.1[plugin-1.7.1.jquery]", "getJQuery!1.8.2[plugin-1.8.2.jquery, lib/jquery-ui-1.9.0.custom]", "getJQuery!1.8.2[plugin-global.jquery, plugin-1.8.2.jquery, lib/jquery-ui-1.9.0.custom]"], function($171, $182, $182_2) {
    var $global;
    $global = window.$ ? window.$ : {
      fn: {
        jquery: "undefined"
      }
    };
    return {
      init: function(name) {
        return describe("getJQuery! loader plugin for: " + name, function() {
          describe('should load jQuery', function() {
            it('$171 should be defined', function() {
              return expect($171).toBeDefined();
            });
            it('$182 should be defined', function() {
              return expect($182).toBeDefined();
            });
            return it('$182_2 should be defined', function() {
              return expect($182_2).toBeDefined();
            });
          });
          describe('at the right version', function() {
            it('$171 should be version 1.7.1', function() {
              expect($171.fn).toBeDefined();
              return expect($171.fn.jquery).toEqual('1.7.1');
            });
            it('$182 should be version 1.8.2', function() {
              expect($182.fn).toBeDefined();
              return expect($182.fn.jquery).toEqual('1.8.2');
            });
            return it('$182_2 should be version 1.8.2', function() {
              expect($182_2.fn).toBeDefined();
              return expect($182_2.fn.jquery).toEqual('1.8.2');
            });
          });
          return describe('without affecting the global jQuery', function() {
            return it('$global should be version 1.6.3', function() {
              return expect($global.fn.jquery).toEqual('1.6.3');
            });
          });
        });
      }
    };
  });

}).call(this);
